MissionRed/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from Home import views as home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view.home, name="home"),
    path('users/', include('users.urls'), name="users"),
    path('doctors/', include('Doctors.urls'), name="Doctors"),
    path('stores/', include('Stores.urls'), name="Stores"),
]

Stores/urls.py
from django.contrib import admin
from django.urls import path
from Stores import views as store_view

app_name = 'Stores'

urlpatterns = [
    path('signup/', store_view.signup, name="signup"),
    path('login/', store_view.login, name="login"),
    path('<name>/dashboard/', store_view.dashboard, name="dashboard"),
    path('<name>/dashboard/<int:order_id>/', store_view.deliver_order, name="deliver_order"),
    path('<name>/dashboard/<int:order_id>/', store_view.cancel_order, name="cancel_order"),
    path('logout/', store_view.logout, name="logout"),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from users import views as user_view

app_name = 'users'

urlpatterns = [
    path('signup/', user_view.signup, name="signup"),
    path('login/', user_view.login, name="login"),
    path('<name>/dashboard/', user_view.dashboard, name='dashboard'),
    path('<name>/doctors/', user_view.doctors, name="doctors"),
    path('<name>/doctors/<int:slot_id>/', user_view.book_slot, name="book_slot"),
    path('<name>/stores/', user_view.stores, name="stores"),
    path('<name>/stores/<store>/', user_view.place_order, name="place_order"),
    path('<name>/stories/', user_view.stories, name="stories"),
    path('<name>/stories/write_portal/', user_view.write_story, name="write_story"),
    path('<name>/stories/read_portal/', user_view.view_story_list, name="view_story_list"),
    path('<name>/stories/read_portal/<int:story_id>/', user_view.read_story, name="read_story"),
    path('logout/', user_view.logout, name="logout"),
]

Stores/models.py
from django.db import models

class Store(models.Model):
    name = models.CharField(max_length=200)
    owner = models.CharField(max_length=200)
    email = models.EmailField(primary_key=True)
    contact = models.CharField(max_length=50)
    location = models.TextField()
    pin_code = models.CharField(max_length=50)
    delivery = models.BooleanField()
    password = models.CharField(max_length=50, null=True)

class Order(models.Model):
    id = models.AutoField(primary_key=True)
    store = models.CharField(max_length=200)
    address = models.TextField()
    customer = models.CharField(max_length=200)
    timing = models.DateTimeField(auto_now_add=True)
    items = models.TextField()
    status = models.CharField(max_length=200, default = 'Pending')

Stores/views.py
from django.shortcuts import redirect, render
from Stores.models import Order, Store

def signup(request):
    if request.method == "POST":
        if request.POST['password1'] == request.POST['password2']:
            try:
                Store.objects.get(email = request.POST['email'])
                return render (request,'Stores/register.html', {'error':'Account with this email already exist!'})
            except Store.DoesNotExist:
                if request.POST['delivery'] == 'on':
                    delivery = True
                else:
                    delivery = False
                store = Store(request.POST['name'], request.POST['owner'], request.POST['email'], request.POST['contact'], request.POST['location'], request.POST['pincode'], delivery, password = request.POST['password1'])
                store.save()
                return redirect('Stores:dashboard', request.POST['name'])
        else:
            return render (request,'Stores/register.html', {'error':'Passwords does not match!'})
    else:
        return render(request,'Stores/register.html')


def login(request):
    if request.method == 'POST':
        store = Store.objects.get(email=request.POST.get('email'))
        if store is None:
            return render(request, 'Stores/login.html', {'error':'No account with this email exist!'})
        else:
            if request.POST.get('password')== getattr(store, 'password'):
                return redirect('Stores:dashboard', getattr(store, 'name'))
            else:
                return render (request,'Stores/login.html', {'error':'Username or password is incorrect!'})
    else:
        return render(request,'Stores/login.html')


def logout(request):
    return render(request, 'index.html')


def dashboard(request, name):
    orders = Order.objects.filter(store = name, status = 'Pending').order_by('timing')
    return render(request, 'Stores/dashboard.html', {'user':name, 'list': orders})

def deliver_order(request, name, order_id):
    order = Order.objects.get(id = order_id)
    order.status = 'Delivered'
    order.save()
    return redirect('Stores:dashboard', name)

def cancel_order(request, name, order_id):
    order = Order.objects.get(id = order_id)
    order.status = 'Canceled'
    order.save()
    return redirect('Stores:dashboard', name)

Stores/templates/Stores/dashboard.html
{% load static %}
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mission Red </title>
    <link rel="icon" href="{% static 'Home/Images/logo.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'Stores/CSS/dashboard.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
</head>
<body>

    <div class="header">
        <a href="{% url 'Stores:logout' %}">Logout</a>
    </div>

    <h1 class="heading">ORDERS</h1>
        <div class="main">
            {% for order in list %}
            <div class="card">
                <div class="card-body">
                    <div class="card-title"> {{order.customer}} </div>
                    <div class="card-text"><strong>Timing: </strong>{{order.timing}}</div>
                    <div class="card-text"><strong>Address: </strong>{{order.address}}</div>
                    <div class="card-text"><strong>Order: </strong>{{order.items}}</div>

                    <div class="flex-container">
                    <button class="button">
                        <a href="{% url 'Stores:deliver_order' name=user order_id=order.id %}" class="link">Deliver</a>
                    </button>
                    <button class="button">
                        <a href="{% url 'Stores:cancel_order' name=user order_id=order.id %}" class="link">Cancel</a>
                    </button>
                    </div>
                    
                </div>
            </div>
            {% endfor %}
        </div>
</body>
</html>

Stores/templates/Stores/login.html
{% load static %}
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mission Red </title>
    <link rel="icon" href="{% static 'Home/Images/logo.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'Stores/CSS/login.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
</head>
<body>

  {% if error %}
  <center>
  <div class="alert alert-danger alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <p>{{error}}</p>
  </div>
  </center>
  {% endif %}

    <div class="form">
        <img src="{% static 'Stores/Images/store.png' %}" class="image">
        <div class="main">
          <h1 class="heading">
            LOGIN
          </h1>
          <form method="POST" action="{% url 'Stores:login' %}" class="regform">
            {% csrf_token %}
              
              EMAIL: <br>
              <input type="text" size="50" name="email" placeholder="E-MAIL" required><br>
              PASSWORD: <br>
              <input type="password" size="50" name="password" placeholder="PASSWORD" required><br>
              <input type="submit" class=" Submit btn btn-primary"  name="submitDetails" value="Login" >
          </form>
        
        </div>
  
    </div>


</body>
</html>

Stores/templates/Stores/register.html
{% load static %}
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mission Red </title>
    <link rel="icon" href="{% static 'Home/Images/logo.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'Stores/CSS/register.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
</head>
<body>

  {% if error %}
  <center>
  <div class="alert alert-danger alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <p>{{error}}</p>
  </div>
  </center>
  {% endif %}

    <div class="form">
        <img src="{% static 'Stores/Images/store.png' %}" class="image">
        <div class="main">
          <h1 class="heading">
            STORE REGISTRATION
          </h1>
          <form method="POST" action="{% url 'Stores:signup' %}" class="regform">
            {% csrf_token %}
              STORE NAME: <br>
              <input type="text" name="name" placeholder="STORE NAME" ><br>
              OWNER NAME: <br>
              <input type="text" name="owner" placeholder="OWNER NAME" ><br>
              EMAIL: <br>
              <input type="text" size="50" name="email" placeholder="E-MAIL" required><br>
              CONTACT NUMBER: <br>
              <input type="text" size="50" name="contact" placeholder="CONTACT NUMBER" required><br>
              LOCATION: <br>
              <input type="text" size="50" name="location" placeholder="LOCATION" required><br>
              PINCODE: <br>
              <input type="text" size="50" name="pincode" placeholder="PINCODE" required><br>
              DELIVERY:
              <input type="checkbox" name="delivery"><br>
              PASSWORD: <br>
              <input type="password" size="50" name="password1" placeholder="PASSWORD" required><br>
              RE-TYPE PASSWORD: <br>
              <input type="password" size="50" name="password2" placeholder="RE-TYPE PASSWORD" required><br>
              <input type="submit" class=" Submit btn btn-primary" name="submitDetails" value="Sign Up" >
          </form>
        
        </div>
  
    </div>

    <div class="container">
        <p>Already have an account? </p>
        <a href= "{% url 'Stores:login' %}"> Log In</a>
    </div>

</body>
</html>