Doctors/urls.py
from django.contrib import admin
from django.urls import path
from Doctors import views as doctor_view

app_name = 'Doctors'

urlpatterns = [
    path('signup/', doctor_view.signup, name='signup'),
    path('login/', doctor_view.login, name='login'),
    path('<name>/dashboard/', doctor_view.dashboard, name='dashboard'),
    path('logout/', doctor_view.logout, name='logout'),
]

MissionRed/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from Home import views as home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view.home, name="home"),
    path('users/', include('users.urls'), name="users"),
    path('doctors/', include('Doctors.urls'), name="Doctors"),
    path('stores/', include('Stores.urls'), name="Stores"),
]

Stores/urls.py
from django.contrib import admin
from django.urls import path
from Stores import views as store_view

app_name = 'Stores'

urlpatterns = [
    path('signup/', store_view.signup, name="signup"),
    path('login/', store_view.login, name="login"),
    path('<name>/dashboard/', store_view.dashboard, name="dashboard"),
    path('<name>/dashboard/<int:order_id>/', store_view.deliver_order, name="deliver_order"),
    path('<name>/dashboard/<int:order_id>/', store_view.cancel_order, name="cancel_order"),
    path('logout/', store_view.logout, name="logout"),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from users import views as user_view

app_name = 'users'

urlpatterns = [
    path('signup/', user_view.signup, name="signup"),
    path('login/', user_view.login, name="login"),
    path('<name>/dashboard/', user_view.dashboard, name='dashboard'),
    path('<name>/doctors/', user_view.doctors, name="doctors"),
    path('<name>/doctors/<int:slot_id>/', user_view.book_slot, name="book_slot"),
    path('<name>/stores/', user_view.stores, name="stores"),
    path('<name>/stores/<store>/', user_view.place_order, name="place_order"),
    path('<name>/stories/', user_view.stories, name="stories"),
    path('<name>/stories/write_portal/', user_view.write_story, name="write_story"),
    path('<name>/stories/read_portal/', user_view.view_story_list, name="view_story_list"),
    path('<name>/stories/read_portal/<int:story_id>/', user_view.read_story, name="read_story"),
    path('logout/', user_view.logout, name="logout"),
]

Home/models.py
from django.db import models

# Create your models here.

Home/views.py
from django.shortcuts import render

def home(request):
    
    return render(request, 'index.html')

Home/templates/index.html
{% load static %}
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mission Red </title>
    <link rel="icon" href="{% static 'Home/Images/logo.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'Home/CSS/index.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
</head>
<body>

      <div class="flex-container">

        <div class="flex-section">
          <h1>#MensturationMatters</h1>
          
          <div class="flex-container">
            <div class="flex-section">
                <h2>Doctors</h2>
                <p>Contribute to the movement by helping young girls during their difficult time.</p>
                <button class="btn-light" >
                  <a href="{% url 'Doctors:signup' %}">SIGN UP</a>
                </button>
            </div>
            <div class="flex-section">
                <h2>Pharmacist</h2>
                <p>Contribute to the movement by providing service at doorsteps of girls in pain.</p>
                <button class="btn-light">
                  <a href="{% url 'Stores:signup' %}">SIGN UP</a>
                </button>
            </div>
            <div class="flex-section">
                <h2>Users</h2>
                <p>Contribute to the movement by raising your voice against illogical stereotypes.</p>
                <button class="btn-light">
                  <a href="{% url 'users:signup' %}">SIGN UP</a>
                </button>
            </div>
            
          </div>
          
        </div>
        <br>
        <img src="{% static 'Home/Images/illustration.png' %}" class="image">
  
      </div>

    
</body>
</html>