Doctors/urls.py
from django.contrib import admin
from django.urls import path
from Doctors import views as doctor_view

app_name = 'Doctors'

urlpatterns = [
    path('signup/', doctor_view.signup, name='signup'),
    path('login/', doctor_view.login, name='login'),
    path('<name>/dashboard/', doctor_view.dashboard, name='dashboard'),
    path('logout/', doctor_view.logout, name='logout'),
]

MissionRed/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from Home import views as home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view.home, name="home"),
    path('users/', include('users.urls'), name="users"),
    path('doctors/', include('Doctors.urls'), name="Doctors"),
    path('stores/', include('Stores.urls'), name="Stores"),
]

Stores/urls.py
from django.contrib import admin
from django.urls import path
from Stores import views as store_view

app_name = 'Stores'

urlpatterns = [
    path('signup/', store_view.signup, name="signup"),
    path('login/', store_view.login, name="login"),
    path('<name>/dashboard/', store_view.dashboard, name="dashboard"),
    path('<name>/dashboard/<int:order_id>/', store_view.deliver_order, name="deliver_order"),
    path('<name>/dashboard/<int:order_id>/', store_view.cancel_order, name="cancel_order"),
    path('logout/', store_view.logout, name="logout"),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from users import views as user_view

app_name = 'users'

urlpatterns = [
    path('signup/', user_view.signup, name="signup"),
    path('login/', user_view.login, name="login"),
    path('<name>/dashboard/', user_view.dashboard, name='dashboard'),
    path('<name>/doctors/', user_view.doctors, name="doctors"),
    path('<name>/doctors/<int:slot_id>/', user_view.book_slot, name="book_slot"),
    path('<name>/stores/', user_view.stores, name="stores"),
    path('<name>/stores/<store>/', user_view.place_order, name="place_order"),
    path('<name>/stories/', user_view.stories, name="stories"),
    path('<name>/stories/write_portal/', user_view.write_story, name="write_story"),
    path('<name>/stories/read_portal/', user_view.view_story_list, name="view_story_list"),
    path('<name>/stories/read_portal/<int:story_id>/', user_view.read_story, name="read_story"),
    path('logout/', user_view.logout, name="logout"),
]

Doctors/models.py
from django.db import models

class Doctor(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(primary_key=True)
    contact = models.CharField(max_length=50)
    specialization = models.CharField(max_length=200)
    registeration_number = models.CharField(max_length=200)
    password = models.CharField(max_length=50)
    is_verified = models.BooleanField(default=False)

class Slot(models.Model):
    id = models.AutoField(primary_key=True)
    slot = models.DateTimeField()
    doctor = models.CharField(max_length=200)
    patient = models.CharField(max_length=200, default=None, blank=True, null=True)
    patient_contact = models.CharField(max_length=200, default=None, blank=True, null=True)
    status = models.CharField(max_length=200, default='Available')

Stores/models.py
from django.db import models

class Store(models.Model):
    name = models.CharField(max_length=200)
    owner = models.CharField(max_length=200)
    email = models.EmailField(primary_key=True)
    contact = models.CharField(max_length=50)
    location = models.TextField()
    pin_code = models.CharField(max_length=50)
    delivery = models.BooleanField()
    password = models.CharField(max_length=50, null=True)

class Order(models.Model):
    id = models.AutoField(primary_key=True)
    store = models.CharField(max_length=200)
    address = models.TextField()
    customer = models.CharField(max_length=200)
    timing = models.DateTimeField(auto_now_add=True)
    items = models.TextField()
    status = models.CharField(max_length=200, default = 'Pending')

users/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    name = models.CharField(max_length=200)
    username = models.CharField(primary_key= True, max_length=200)
    email = models.EmailField()
    contact = models.CharField(max_length=50)
    password = models.CharField(max_length=50, null=True)

class Schedule(models.Model):
    id = models.AutoField(primary_key=True)
    start_date = models.DateField()
    end_date = models.DateField()
    user = models.CharField(max_length=200)

class Posts(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    created_on = models.DateField(auto_now=True)
    content = models.TextField()

    class meta:
        ordering = ['-created_on']

Doctors/views.py
import datetime
from django.shortcuts import redirect, render
from Doctors.models import Doctor, Slot

def signup(request):
    if request.method == "POST":
        if request.POST['password1'] == request.POST['password2']:
            try:
                Doctor.objects.get(email = request.POST['email'])
                return render (request,'Doctors/register.html', {'error':'Account with this email already exist!'})
            except Doctor.DoesNotExist:
                user = Doctor(request.POST['name'], request.POST['email'], request.POST['contact'], request.POST['specialization'], request.POST['registeration'], password = request.POST['password1'])
                user.save()
                return redirect('Doctors:dashboard', getattr(user, 'name'))
        else:
            return render (request,'Doctors/register.html', {'error':'Passwords does not match!'})
    else:
        return render(request,'Doctors/register.html')


def login(request):
    if request.method == 'POST':
        user = Doctor.objects.get(email = request.POST.get('email'))
        if user is None:
            return render(request,'Doctors/login.html', {'error':'No account with this email exist!'})
        else:
            if request.POST.get('password') == getattr(user, 'password'):
                return redirect('Doctors:dashboard', getattr(user, 'name'))
            else:
                return render (request,'Doctors/login.html', {'error':'Username or password is incorrect!'})
    else:
        return render(request,'Doctors/login.html')


def logout(request):
    return render(request, 'index.html')


def dashboard(request, name):
    doctor = Doctor.objects.get(name = name)

    if (request.method == 'POST') and (getattr(doctor, 'is_verified')==False):
        return render(request, 'Doctors/dashboard.html', {'user':name, 'message':"Wait for verification by admin to schedule appointments!!"})

    if (request.method == 'POST') and (getattr(doctor, 'is_verified')==True):
        date = request.POST['date']
        time = request.POST['time']

        timing = datetime.datetime.combine(datetime.datetime.strptime(date,"%Y-%m-%d"), datetime.datetime.strptime(time, "%H:%M").time())
        slots = Slot(slot = timing, doctor = name)
        slots.save()
    slots = Slot.objects.filter(doctor = name).order_by('slot')
    return render(request, 'Doctors/dashboard.html', {'user': name, 'list':slots})

Stores/views.py
from django.shortcuts import redirect, render
from Stores.models import Order, Store

def signup(request):
    if request.method == "POST":
        if request.POST['password1'] == request.POST['password2']:
            try:
                Store.objects.get(email = request.POST['email'])
                return render (request,'Stores/register.html', {'error':'Account with this email already exist!'})
            except Store.DoesNotExist:
                if request.POST['delivery'] == 'on':
                    delivery = True
                else:
                    delivery = False
                store = Store(request.POST['name'], request.POST['owner'], request.POST['email'], request.POST['contact'], request.POST['location'], request.POST['pincode'], delivery, password = request.POST['password1'])
                store.save()
                return redirect('Stores:dashboard', request.POST['name'])
        else:
            return render (request,'Stores/register.html', {'error':'Passwords does not match!'})
    else:
        return render(request,'Stores/register.html')


def login(request):
    if request.method == 'POST':
        store = Store.objects.get(email=request.POST.get('email'))
        if store is None:
            return render(request, 'Stores/login.html', {'error':'No account with this email exist!'})
        else:
            if request.POST.get('password')== getattr(store, 'password'):
                return redirect('Stores:dashboard', getattr(store, 'name'))
            else:
                return render (request,'Stores/login.html', {'error':'Username or password is incorrect!'})
    else:
        return render(request,'Stores/login.html')


def logout(request):
    return render(request, 'index.html')


def dashboard(request, name):
    orders = Order.objects.filter(store = name, status = 'Pending').order_by('timing')
    return render(request, 'Stores/dashboard.html', {'user':name, 'list': orders})

def deliver_order(request, name, order_id):
    order = Order.objects.get(id = order_id)
    order.status = 'Delivered'
    order.save()
    return redirect('Stores:dashboard', name)

def cancel_order(request, name, order_id):
    order = Order.objects.get(id = order_id)
    order.status = 'Canceled'
    order.save()
    return redirect('Stores:dashboard', name)

users/views.py
from django.shortcuts import render,redirect
from users.models import Schedule, Users, Posts
from Stores.models import Store, Order
from Doctors.models import Slot
import datetime

def signup(request):
    if request.method == "POST":
        if request.POST['password1'] == request.POST['password2']:
            try:
                Users.objects.get(username = request.POST['username'])
                return render (request,'users/register.html', {'error':'Username is already taken!'})
            except Users.DoesNotExist:
                user = Users(request.POST['name'], request.POST['username'], request.POST['email'], request.POST['contact'], password = request.POST['password1'])
                user.save()
                return redirect('users:dashboard', getattr(user, 'username'))
        else:
            return render (request,'users/register.html', {'error':'Passwords does not match!'})
    else:
        return render(request,'users/register.html')


def login(request):
    if request.method == 'POST':
        user = Users.objects.get(username=request.POST.get('username'))
        if user is None:
            return render(request, 'users/login.html', {'error':'No account with this username exist!'})
        else:
            if request.POST.get('password') == getattr(user, 'password'):
                return redirect('users:dashboard', getattr(user, 'username'))
            else:
                return render(request,'users/login.html', {'error':'Username or password is incorrect!'})
    else:
        return render(request,'users/login.html')


def logout(request):
    return render(request, 'index.html')


def dashboard(request, name):
    if request.method == 'POST':
        start = request.POST['start_date']
        end = request.POST['end_date']

        start_date = datetime.datetime.strptime(start,'%Y-%m-%d')
        end_date = datetime.datetime.strptime(end,'%Y-%m-%d')
        schedule = Schedule(start_date=start_date, end_date=end_date, user = name)
        schedule.save()
        return redirect('users:dashboard', name)
    schedule = Schedule.objects.filter(user = name).order_by('id')[:5:-1]
    return render(request, 'users/dashboard.html', {'user': name, 'list': schedule})


def doctors(request, name):
    slots_list = Slot.objects.filter(status= 'Available')
    return render(request, 'users/doctor.html', {'list': slots_list, 'user': name})

def book_slot(request, name, slot_id):
    slot = Slot.objects.get(id = slot_id)
    user = Users.objects.get(name = name)
    slot.patient = name
    slot.patient_contact = user.contact
    slot.status = 'Booked'
    slot.save()
    return redirect('users:doctors', name)

def stores(request, name):
    stores_list = Store.objects.all()
    return render(request, 'users/stores.html', {'user': name, 'list': stores_list})

def place_order(request, name, store):
    if request.method == 'POST':
        order = Order(store=store, customer=name, address=request.POST.get('address'), items=request.POST.get('items'))
        order.save()
        return redirect('users:stores', name)
    orders = Order.objects.filter(store=store, customer=name)
    return render(request, 'users/order.html', {'user':name, 'store':store, 'list':orders})


def stories(request, name):
    return render(request, 'users/stories.html', {'user':name})


def write_story(request, name):
    if request.method == 'POST':
        story = Posts(title=request.POST['title'], author=name, content=request.POST['story'])
        story.save()
        return render(request, 'users/stories.html', {'user':name})
    return render(request, 'users/write_portal.html', {'user':name})


def view_story_list(request, name):
    story_list = Posts.objects.all()
    return render(request, 'users/read_portal.html', {'user':name, 'list':story_list})


def read_story(request, name, story_id):
    story = Posts.objects.get(id = story_id)
    return render(request, 'users/story_view.html', {'user':name, 'story':story})

users/templates/users/doctor.html
{% load static %}
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mission Red </title>
    <link rel="icon" href="{% static 'Home/Images/logo.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'users/CSS/doctor.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light ">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
          <a class="nav-link" href="{% url 'users:doctors' user%}">DOCTORS</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'users:stores' user%}">STORES</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'users:stories' user%}">STORIES</a>
          </li>
          <li class="nav-item ">
          <a class="nav-link" href="{% url 'users:logout' %}">LOGOUT</a>
          </li>    
        </ul>
        </div>
  
    </nav>

    <h1 class="heading">SCHEDULE  YOUR  APPOINTMENT</h1>

    <div class="main">
        {% for slots in list %}
        <div class="card">
            <div class="card-body">
                <div class="card-title"> {{slots.doctor}} </div>
                <div class="card-text">Timings: {{slots.slot}}</div>
                <button class="button">
                    <a href="{% url 'users:book_slot' name=user slot_id=slots.id %}">Book slot</a>
                </button>
            </div>
        </div>
        {% endfor %}
    </div>
    
</body>
</html>

users/templates/users/order.html
{% load static %}
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mission Red </title>
    <link rel="icon" href="{% static 'Home/Images/logo.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'users/CSS/order.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light ">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'users:doctors' user %}">DOCTORS</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'users:stores' user %}">STORES</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:stories' user %}">STORIES</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'users:logout' %}">LOGOUT</a>
      </li>    
    </ul>
    </div>

  </nav>

  <div class="flex-container">

    <img src="{% static 'users/Images/store.png' %}">

    <div class="form">
        <div class="main">
          <h1 class="form-heading">
            Orders
          </h1>
          <form method="POST" action="{% url 'users:place_order' name=user store=store %}" >
            {% csrf_token %}
              ADDRESS:
              <input type="text" name="address" placeholder="ADDRESS" required>
              
              ITEM LIST: <br>
              <textarea name="items" placeholder="Place your order...." required></textarea><br>
              <input type="submit" class=" submit btn" name="submitDetails" value="Order" >
          </form>
        </div>
    </div>

  </div>

  <h1 class="heading">ORDERS</h1>

    {% for order in list %}
      <div class="card">
        <div class="card-body">
          <div class="card-title"> {{order.store}} </div>
          <div class="card-text">Timings: {{order.timing}}</div>
          <div class="card-text">Order Content: {{order.items}}</div>
          <div class="card-text">Status: {{order.status}}</div>
        </div>
      </div>
            
    {% endfor %}
    
</body>
</html>

users/templates/users/read_portal.html
{% load static %}
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mission Red </title>
    <link rel="icon" href="{% static 'Home/Images/logo.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'users/CSS/read_portal.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light ">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
          <a class="nav-link" href="{% url 'users:doctors' user %}">DOCTORS</a>
          </li>
          <li class="nav-item ">
          <a class="nav-link" href="{% url 'users:stores' user %}">STORES</a>
          </li>
          <li class="nav-item active">
          <a class="nav-link" href="{% url 'users:stories' user %}">STORIES</a>
          </li>
          <li class="nav-item ">
          <a class="nav-link" href="{% url 'users:logout' %}">LOGOUT</a>
          </li>    
        </ul>
        </div>
  
    </nav>
    
    <h1 class="heading">READING PORTAL</h1>
    
    <div class="main">
        {% for story in list %}
        <div class="card">
            <div class="card-body">
                <div class="card-title"> {{story.title}} </div>
                <div class="card-text">Author: {{story.author}}</div>
                <div class="card-text">Created On: {{story.created_on}}</div>
                <button class="button">
                    <a href="{% url 'users:read_story' name=user story_id=story.id %}">Read</a>
                </button>
            </div>
        </div> 
        {% endfor %}
    </div>

</body>
</html>

users/templates/users/stores.html
{% load static %}
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mission Red </title>
    <link rel="icon" href="{% static 'Home/Images/logo.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'users/CSS/stores.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
</head>
<body>
    
    <nav class="navbar navbar-expand-md navbar-light ">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
          <a class="nav-link" href="{% url 'users:doctors' user %}">DOCTORS</a>
          </li>
          <li class="nav-item active">
          <a class="nav-link" href="{% url 'users:stores' user %}">STORES</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'users:stories' user %}">STORIES</a>
          </li>
          <li class="nav-item ">
          <a class="nav-link" href="{% url 'users:logout' %}">LOGOUT</a>
          </li>    
        </ul>
        </div>
  
    </nav>
    
    <h1 class="heading">STORES</h1>
        
    <div class="main">
        {% for store in list %}
        <div class="card">
            <div class="card-body">
                <div class="card-title"> {{store.name}} </div>
                <div class="card-text">Owner: {{store.owner}}</div>
                <div class="card-text">Contact Number: {{store.contact}}</div>
                <div class="card-text">Location: {{store.location}}</div>
                <button class="button">
                    <a href="{% url 'users:place_order' name=user store=store.name %}">Order</a>
                </button>
            </div>
        </div>
        
        {% endfor %}
    </div>
    
</body>
</html>

users/templates/users/stories.html
{% load static %}
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mission Red </title>
    <link rel="icon" href="{% static 'Home/Images/logo.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'users/CSS/stories.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-light ">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'users:doctors' user %}">DOCTORS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:stores' user %}">STORES</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'users:stories' user %}">STORIES</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'users:logout' %}">LOGOUT</a>
          </li>    
        </ul>
        </div>
  
      </nav>

    <div class="flex-container">

        <div class="card">
            <div class="card-body">
                <div class="card-title">Writing Portal</div>
                <div class="card-text">Periods are not too gross, too weird or too inappropriate to talk about it. So, let's go with the flow and discuss it openly without any shame!!</div>
                <button class="btn btn-primary">
                    <a href="{% url 'users:write_story' user %}">Write</a>
                </button>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <div class="card-title">Reading Portal</div>
                <div class="card-text">Periods are not too gross, too weird or too inappropriate to talk about it. So, let's go with the flow and discuss it openly without any shame!!</div>
                <button class="btn btn-primary">
                    <a href="{% url 'users:view_story_list' user %}">Read</a>
                </button>
            </div>
        </div>

    </div>
</body>
</html>

users/templates/users/write_portal.html
{% load static %}
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mission Red </title>
    <link rel="icon" href="{% static 'Home/Images/logo.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'users/CSS/write_portal.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-light ">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'users:doctors' user %}">DOCTORS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:stores' user %}">STORES</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'users:stories' user %}">STORIES</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'users:logout' %}">LOGOUT</a>
          </li>    
        </ul>
        </div>
  
    </nav>

    <div class="flex-container">

    <img src="{% static 'users/Images/blog.png' %}" class="image">

    <div class="form">
        <div class="main">
          <h1 class="heading">
            Writing Portal
          </h1>
          <form method="POST" action="{% url 'users:write_story' user %}" >
            {% csrf_token %}
              
              TITLE: <br>
              <input type="text" name="title" required><br>
              STORY: <br>
              <textarea name="story" placeholder="Share your story...." required></textarea><br>
              <input type="submit" class=" submit btn" name="submitDetails" value="POST" >
          </form>
        </div>
  
    </div>
    </div>
    
</body>
</html>