Doctors/urls.py
from django.contrib import admin
from django.urls import path
from Doctors import views as doctor_view

app_name = 'Doctors'

urlpatterns = [
    path('signup/', doctor_view.signup, name='signup'),
    path('login/', doctor_view.login, name='login'),
    path('<name>/dashboard/', doctor_view.dashboard, name='dashboard'),
    path('logout/', doctor_view.logout, name='logout'),
]

MissionRed/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from Home import views as home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view.home, name="home"),
    path('users/', include('users.urls'), name="users"),
    path('doctors/', include('Doctors.urls'), name="Doctors"),
    path('stores/', include('Stores.urls'), name="Stores"),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from users import views as user_view

app_name = 'users'

urlpatterns = [
    path('signup/', user_view.signup, name="signup"),
    path('login/', user_view.login, name="login"),
    path('<name>/dashboard/', user_view.dashboard, name='dashboard'),
    path('<name>/doctors/', user_view.doctors, name="doctors"),
    path('<name>/doctors/<int:slot_id>/', user_view.book_slot, name="book_slot"),
    path('<name>/stores/', user_view.stores, name="stores"),
    path('<name>/stores/<store>/', user_view.place_order, name="place_order"),
    path('<name>/stories/', user_view.stories, name="stories"),
    path('<name>/stories/write_portal/', user_view.write_story, name="write_story"),
    path('<name>/stories/read_portal/', user_view.view_story_list, name="view_story_list"),
    path('<name>/stories/read_portal/<int:story_id>/', user_view.read_story, name="read_story"),
    path('logout/', user_view.logout, name="logout"),
]

Doctors/models.py
from django.db import models

class Doctor(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(primary_key=True)
    contact = models.CharField(max_length=50)
    specialization = models.CharField(max_length=200)
    registeration_number = models.CharField(max_length=200)
    password = models.CharField(max_length=50)
    is_verified = models.BooleanField(default=False)

class Slot(models.Model):
    id = models.AutoField(primary_key=True)
    slot = models.DateTimeField()
    doctor = models.CharField(max_length=200)
    patient = models.CharField(max_length=200, default=None, blank=True, null=True)
    patient_contact = models.CharField(max_length=200, default=None, blank=True, null=True)
    status = models.CharField(max_length=200, default='Available')

Doctors/views.py
import datetime
from django.shortcuts import redirect, render
from Doctors.models import Doctor, Slot

def signup(request):
    if request.method == "POST":
        if request.POST['password1'] == request.POST['password2']:
            try:
                Doctor.objects.get(email = request.POST['email'])
                return render (request,'Doctors/register.html', {'error':'Account with this email already exist!'})
            except Doctor.DoesNotExist:
                user = Doctor(request.POST['name'], request.POST['email'], request.POST['contact'], request.POST['specialization'], request.POST['registeration'], password = request.POST['password1'])
                user.save()
                return redirect('Doctors:dashboard', getattr(user, 'name'))
        else:
            return render (request,'Doctors/register.html', {'error':'Passwords does not match!'})
    else:
        return render(request,'Doctors/register.html')


def login(request):
    if request.method == 'POST':
        user = Doctor.objects.get(email = request.POST.get('email'))
        if user is None:
            return render(request,'Doctors/login.html', {'error':'No account with this email exist!'})
        else:
            if request.POST.get('password') == getattr(user, 'password'):
                return redirect('Doctors:dashboard', getattr(user, 'name'))
            else:
                return render (request,'Doctors/login.html', {'error':'Username or password is incorrect!'})
    else:
        return render(request,'Doctors/login.html')


def logout(request):
    return render(request, 'index.html')


def dashboard(request, name):
    doctor = Doctor.objects.get(name = name)

    if (request.method == 'POST') and (getattr(doctor, 'is_verified')==False):
        return render(request, 'Doctors/dashboard.html', {'user':name, 'message':"Wait for verification by admin to schedule appointments!!"})

    if (request.method == 'POST') and (getattr(doctor, 'is_verified')==True):
        date = request.POST['date']
        time = request.POST['time']

        timing = datetime.datetime.combine(datetime.datetime.strptime(date,"%Y-%m-%d"), datetime.datetime.strptime(time, "%H:%M").time())
        slots = Slot(slot = timing, doctor = name)
        slots.save()
    slots = Slot.objects.filter(doctor = name).order_by('slot')
    return render(request, 'Doctors/dashboard.html', {'user': name, 'list':slots})

Doctors/templates/Doctors/dashboard.html
{% load static %}
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mission Red </title>
    <link rel="icon" href="{% static 'Home/Images/logo.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'Doctors/CSS/dashboard.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
</head>
<body>

  {% if message %}
    <center>
    <div class="alert alert-danger alert-dismissible">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <p>{{message}}</p>
    </div>
    </center>
  {% endif %}
    
  <div class="header">
    <a href="{% url 'Doctors:logout' %}">Logout</a>
  </div>
    

    <div class="flex-container">

      <img src="{% static 'Doctors/Images/schedule.png'%}" class="image">

      <div class="form">
        <div class="main">
          <h1 class="form-heading">
            Appointment Slot
          </h1>
          <form method="POST" action="{% url 'Doctors:dashboard' user %}" class="regform">
            {% csrf_token %}
              
              DATE: <br>
              <input type="date" name="date" required><br>
              TIME: <br>
              <input type="time" name="time" required><br>
              <input type="submit" class=" Submit btn btn-primary" name="submitDetails" value="Add" >
          </form>
        </div>
      </div>

    </div>

    <h1 class="heading"> SCHEDULED APPOINTMENTS </h1>

    <div class="slot-main">
      {% for slots in list %}
      <div class="card">
          <div class="card-body">
              <div class="card-title"> {{slots.doctor}} </div>
              <div class="card-text"><strong>Timing: </strong>{{slots.slot}}</div>
              <div class="card-text"><strong>Patient: </strong>{{slots.patient}}</div>
              <div class="card-text"><strong>Patient Contact: </strong>{{slots.patient_contact}}</div>
              <div class="card-text"><strong>Status: </strong>{{slots.status}}</div>
          </div>
      </div>
      {% endfor %}
    </div>

    
</body>
</html>

Doctors/templates/Doctors/login.html
{% load static %}
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mission Red </title>
    <link rel="icon" href="{% static 'Home/Images/logo.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'Doctors/CSS/login.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
</head>
<body>

    {% if error %}
    <center>
    <div class="alert alert-danger alert-dismissible">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <p>{{error}}</p>
    </div>
    </center>
    {% endif %}

    <div class="form">

        <img src="{% static 'Doctors/Images/doctor.png' %}" class="image">

        <div class="main">
          <h1 class="heading">
            LOGIN
          </h1>
          <form method="POST" action="{% url 'Doctors:login' %}" class="regform">
            {% csrf_token %}
              
              EMAIL: <br>
              <input type="text" size="50" name="email" placeholder="E-MAIL" required><br>
              PASSWORD: <br>
              <input type="password" size="50" name="password" placeholder="PASSWORD" required><br>
              <input type="submit" class=" Submit btn btn-primary"  name="submitDetails" value="Login" >
          </form>
        
        </div>
  
    </div>


</body>
</html>

Doctors/templates/Doctors/register.html
{% load static %}
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mission Red </title>
    <link rel="icon" href="{% static 'Home/Images/logo.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'Doctors/CSS/register.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
</head>
<body>

  {% if error %}
  <center>
  <div class="alert alert-danger alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <p>{{error}}</p>
  </div>
  </center>
  {% endif %}

    <div class="form">

        <img src="{% static 'Doctors/Images/doctor.png' %}" class="image">
        
        <div class="main">
          <h1 class="heading">
            DOCTOR REGISTRATION
          </h1>
          <form method="POST" action="{% url 'Doctors:signup' %}" class="regform">
            {% csrf_token %}
              NAME: <br>
              <input type="text" name="name" placeholder="NAME" ><br>
              EMAIL: <br>
              <input type="text" size="50" name="email" placeholder="E-MAIL" required><br>
              CONTACT NUMBER: <br>
              <input type="text" size="50" name="contact" placeholder="CONTACT NUMBER" required><br>
              SPECIALIZATION: <br>
              <input type="text" size="50" name="specialization" placeholder="SPECIALIZATION" required><br>
              REGISTERATION NUMBER: <br>
              <input type="text" size="50" name="registeration" placeholder="REGISTERATION NUMBER" required><br>
              PASSWORD: <br>
              <input type="password" size="50" name="password1" placeholder="PASSWORD" required><br>
              RE-TYPE PASSWORD: <br>
              <input type="password" size="50" name="password2" placeholder="RE-TYPE PASSWORD" required><br>
              <input type="submit" class=" Submit btn btn-primary" name="submitDetails" value="Sign Up" >
          </form>
        
        </div>
  
    </div>

    <div class="container">
        <p>Already have an account? </p>
        <a href= "{% url 'Doctors:login' %}"> Log In</a>
    </div>

</body>
</html>